version: "3"

services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      - GOPATH=/go

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
  pgdata:
